trigger: 
- main

pool: 
   vmImage: windows 

jobs:
- deployment: VMDeploy
displayName: Deploy to VM
environment: 
   name: ContosoDeploy
   resourceType: VirtualMachine
   tags: Devopster
strategy:
   runOnce:
   deploy:   
      steps:
      - script: echo "Hello world"